[package]
name = "bananar"
version = "0.0.0"
edition = "2021"

[dependencies]
nix = { version = "0.27.1", default-features = false, features = ["fs", "mman"] }
wayland-client = "0.31.1"
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }
